apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels:
    name: nginx
    team: finance
    enviroment: staging
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
